baseURL = "https://gohugo.io"
title = "STIX Theme"
author = "Eddie Hillenbrand"
copyright = "Copyright © 2020 Eddie Hillenbrand"

theme = "stix"
enableEmoji = true
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"


[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10


[taxonomies]
category = "categories"
tag = "tags"
series = "series"


[params]
title = "STIX Theme for Hugo"
Tagline = "Development Site"
description = "Development site for the STIX-Hugo theme."
images = [""]



[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true


[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
