#+TITLE: Fonts Showcase
#+DATE: 2022-01-27T08:26:20-08:00
#+AUTHOR:
#+DESCRIPTION:
#+TAGS[]:
#+SERIES[]:
#+IMAGES[]:
#+VIDEOS[]:
#+AUDIO[]:

* Body Fonts

Body text in STIX Fonts. The STIX "fonts are intended to satisfy the
demanding needs of authors, publishers, printers, and others working
in the scientific, medical, and technical fields."

** Formatting

Want something *bold* use =*bold*=. Want something /italic/ use
=/italic/=. Want something _underlined_ use =_underlined_=. Want
something +strikethrough+ use =+strikethrough+=. And lastly, want
something =monospaced= use ~=monospaced=~ or =~monospaced~=.


** Subscripts and Superscripts

Text characters set below or above the line of type for a font/size
combination are necessary for technical writing. Subscripts and
superscripts are achieved in the same way as in TeX or LaTeX. Use
=_{subscript text}= for subscript and =^{superscript text}= for
superscript.

The radius of the sun is R_{sun} = 6.96 \times 10^{8} m.  On the other
hand, the radius of Alpha Centauri is R_{Alpha Centauri} = 1.28 \times
R_{sun}.


** Special Symbols

There are many special symbols and non-Latin alphabets that can be
inserted in an Org document. The syntax is like TeX or LaTeX too.

Given a circle \Gamma of diameter d, the length of its circumference
is \pid. We can type \alpha as =\alpha=, \beta as =\beta=, and \chi as
=\chi=. In Org mode if you need a symbol in a word or formula it can
be terminated with a pair of curly braces like so =\pi{}d=, but in
Hugo, using [[https://github.com/niklasfasching/go-org][go-org]] you only need =\pid=---seems like it could
introduce ambiguity.

Some other symbols include \copy as =\copy=, \dag as =\dag=, and
\times as seen in the subscript/superscript section above as
=\times=. There's \pm as =\pm= or =\plusmn=. There's \frac12 as
=\frac12= and there's \frac34 as =\frac34=. There's x \to \infin,
typed as =x \to \infin=. Don't forget the en dash -- or the em dash
---, respectively =--= and =---=.

A large centered =\lambda= using =#+ATTR_HTML: :class text-center font-size-lg=
#+ATTR_HTML: :class text-center font-size-lg
#+begin_lead
\lambda
#+end_lead

* Heading Fonts

Headings structure documents into sections and subsections. Headings
are displayed in Helvetica.

* Top or first level headline
Curabitur blandit tempus ardua ridiculus sed magna.

** Second level
Me non paenitet nullum festiviorem excogitasse ad hoc.

*** Third level
Ab illo tempore, ab est sed immemorabili.

**** Forth level
Sed haec quis possit intrepidus aestimare tellus.

***** Fifth level
Nihil hic munitissimus habendi senatus locus, nihil horum?

****** Sixth level
Quae vero auctorem tractata ab fiducia dicuntur.

* Code Fonts

A good code font cleary differentiates i, 1, l, L, I, |, o, O, and 0. In
DejaVu Sans Mono the characters are =i1lLI|oO0=.

#+begin_src c
int main(int argc, char **argv)
{
    return 0;
}
#+end_src

The next code block is used to check if the styling can display 80
character lines without overflow. The block is made up of lines
contains the first 80 characters of a base-85 encoding called [[https://rfc.zeromq.org/spec:32/Z85/][Z85]].

#+BEGIN_SRC text
0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.-:+=^!/*?&<>()[]{
0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.-:+=^!/*?&<>()[]{
0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.-:+=^!/*?&<>()[]{
#+END_SRC

Now we must check how a code block that overflows looks.

#+BEGIN_SRC objc
+ (nullable NSURL *)URLForResource:(nullable NSString *)name withExtension:(nullable NSString *)ext subdirectory:(nullable NSString *)subpath inBundleWithURL:(NSURL *)bundleURL API_AVAILABLE(macos(10.6), ios(4.0), watchos(2.0), tvos(9.0));
#+END_SRC

Code with formatting

#+begin_pre
Something *bold*, something /italic/, some Greek \lambda, some math
x^{3}, a \le b^{2} \plus C, and subscripts_{i} too.
#+end_pre

* More on the STIX Fonts

The description of the STIX Font embeded in the v1.x font files is as
follows:

#+begin_quote
Arie de Ruiter, who in 1995 was Head of Information Technology
Development at Elsevier Science, made a proposal to the STI Pub group,
an informal group of publishers consisting of representatives from the
American Chemical Society (ACS), American Institute of Physics (AIP),
American Mathematical Society (AMS), American Physical Society (APS),
Elsevier, and Institute of Electrical and Electronics Engineers
(IEEE). De Ruiter encouraged the members to consider development of a
series of Web fonts, which he proposed should be called the Scientific
and Technical Information eXchange, or STIX, Fonts. All STI Pub member
organizations enthusiastically endorsed this proposal, and the STI Pub
group agreed to embark on what has become a twelve-year project. The
goal of the project was to identify all alphabetic, symbolic, and
other special characters used in any facet of scientific publishing
and to create a set of Unicode-based fonts that would be distributed
free to every scientist, student, and other interested party
worldwide. The fonts would be consistent with the emerging Unicode
standard, and would permit universal representation of every
character. With the release of the STIX fonts, de Ruiter's vision has
been realized.

@@html: <span class="attribution">&mdash; STIX 1.1.0 STIXGeneral.otf</span>@@
#+end_quote

The description of the STIX Font embeded in the v2.x font files is as
follows:

#+begin_quote
The Scientific and Technical Information eXchange (STIX) fonts are
intended to satisfy the demanding needs of authors, publishers,
printers, and others working in the scientific, medical, and technical
fields. They combine a comprehensive Unicode-based collection of
mathematical symbols and alphabets with a set of text faces suitable
for professional publishing. The fonts are available royalty-free
under the SIL Open Font License.

@@html: <span class="attribution">&mdash; STIX 2.13 b170 STIXTwoText-Regular.otf</span>@@
#+end_quote

* More on DejaVu Sans Mono

The lede paragraph from the DejaVu fonts webpage follows:

#+begin_quote
The DejaVu fonts are a font family based on the Vera Fonts. Its
purpose is to provide a wider range of characters while maintaining
the original look and feel through the process of collaborative
development (see authors), under a Free license.

@@html: <span class="attribution">&mdash; https://dejavu-fonts.github.io</span>@@
#+end_quote

A quote from [[https://en.wikipedia.org/wiki/DejaVu_fonts#DejaVu_Sans_Mono][Wikipedia]] follows:

#+begin_quote
The DejaVu Sans Mono typeface in particular is suitable for technical
contexts, since it clearly distinguishes "l" (lowercase L) from "1"
(one) and from "I" (uppercase i); also it clearly distinguishes "0"
(zero, null) from "O" (uppercase o).

@@html: <span class="attribution">&mdash; Wikipedia</span>@@
#+end_quote
