#+TITLE: Org-mode Syntax Guide
#+DATE: 2020-01-01T07:51:20-08:00
#+AUTHOR: Hugo Authors
#+DESCRIPTION: Sample article showcasing Org syntax and formatting.
#+TAGS[]: org css html themes
#+CATEGORIES[]: themes syntax
#+SERIES[]: "Themes Guide"
#+IMAGES[]:
#+VIDEOS[]:
#+AUDIO[]:
#+DRAFT: false
#+STARTUP: showall

This article offers a sample of basic Org syntax that can be used
in Hugo content files, also it shows whether basic HTML elements are
decorated with CSS in a Hugo theme.

** Headings
   :PROPERTIES:
   :CUSTOM_ID: headings
   :END:

The following HTML =<h1>=---=<h6>= elements represent six levels of
section headings. =<h1>= is the highest section level while =<h6>= is
the lowest.

* H1
  :PROPERTIES:
  :CUSTOM_ID: h1
  :END:

** H2
   :PROPERTIES:
   :CUSTOM_ID: h2
   :END:

*** H3
    :PROPERTIES:
    :CUSTOM_ID: h3
    :END:

**** H4
     :PROPERTIES:
     :CUSTOM_ID: h4
     :END:

***** H5
      :PROPERTIES:
      :CUSTOM_ID: h5
      :END:

****** H6
       :PROPERTIES:
       :CUSTOM_ID: h6
       :END:

** Paragraph
   :PROPERTIES:
   :CUSTOM_ID: paragraph
   :END:

Xerum, quo qui aut unt expliquam qui dolut labo. Aque venitatiusda cum,
voluptionse latur sitiae dolessi aut parist aut dollo enim qui voluptate
ma dolestendit peritin re plis aut quas inctum laceat est volestemque
commosa as cus endigna tectur, offic to cor sequas etum rerum idem
sintibus eiur? Quianimin porecus evelectur, cum que nis nust voloribus
ratem aut omnimi, sitatur? Quiatem. Nam, omnis sum am facea corem alique
molestrunt et eos evelece arcillit ut aut eos eos nus, sin conecerem
erum fuga. Ri oditatquam, ad quibus unda veliamenimin cusam et facea
ipsamus es exerum sitate dolores editium rerore eost, temped molorro
ratiae volorro te reribus dolorer sperchicium faceata tiustia prat.

Itatur? Quiatae cullecum rem ent aut odis in re eossequodi nonsequ
idebis ne sapicia is sinveli squiatum, core et que aut hariosam ex eat.

** Blockquotes
   :PROPERTIES:
   :CUSTOM_ID: blockquotes
   :END:

The blockquote element represents content that is quoted from another
source, optionally with a citation which must be within a =footer= or
=cite= element, and optionally with in-line changes such as annotations
and abbreviations.

**** Blockquote without attribution
     :PROPERTIES:
     :CUSTOM_ID: blockquote-without-attribution
     :END:

#+BEGIN_QUOTE
  Tiam, ad mint andaepu dandae nostion secatur sequo quae. *Note* that
  you can use /Org syntax/ within a blockquote.
#+END_QUOTE

**** Blockquote with attribution
     :PROPERTIES:
     :CUSTOM_ID: blockquote-with-attribution
     :END:

#+BEGIN_QUOTE
  Don't communicate by sharing memory, share memory by communicating.
  --- Rob Pike[fn:1]
#+END_QUOTE

** Tables
   :PROPERTIES:
   :CUSTOM_ID: tables
   :END:

Tables aren't part of the core Org spec, but Hugo supports supports
them out-of-the-box.

| Name    | Age   |
|---------+-------|
| Bob     | 27    |
| Alice   | 23    |

**** Inline Org within tables
     :PROPERTIES:
     :CUSTOM_ID: inline-org-within-tables
     :END:

| Inline      | Org      | In                   | Table    |
|-------------+---------------+----------------------+----------|
| /italics/   | *bold*        | +strikethrough+      | =code=   |
#+TBLFM:

** Code Blocks
   :PROPERTIES:
   :CUSTOM_ID: code-blocks
   :END:

**** Code block with backticks
     :PROPERTIES:
     :CUSTOM_ID: code-block-with-backticks
     :END:

#+BEGIN_SRC html
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Example HTML5 Document</title>
  </head>
  <body>
    <p>Test</p>
  </body>
  </html>
#+END_SRC

**** Code block indented with four spaces
     :PROPERTIES:
     :CUSTOM_ID: code-block-indented-with-four-spaces
     :END:

#+BEGIN_SRC text
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Example HTML5 Document</title>
  </head>
  <body>
    <p>Test</p>
  </body>
  </html>
#+END_SRC

**** Code block with Hugo's internal highlight shortcode
     :PROPERTIES:
     :CUSTOM_ID: code-block-with-hugos-internal-highlight-shortcode
     :END:

{{< highlight html >}}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Example HTML5 Document</title>
</head>
<body>
  <p>Test</p>
</body>
</html>
{{< /highlight >}}

** List Types
   :PROPERTIES:
   :CUSTOM_ID: list-types
   :END:

**** Ordered List
     :PROPERTIES:
     :CUSTOM_ID: ordered-list
     :END:

1. First item
2. Second item
3. Third item

**** Unordered List
     :PROPERTIES:
     :CUSTOM_ID: unordered-list
     :END:

- List item
- Another item
- And another item

**** Nested list
     :PROPERTIES:
     :CUSTOM_ID: nested-list
     :END:

- Item A

  1. First Sub-item
  2. Second Sub-item

- Item B

  1. Sub-item one
  2. Sub-item two

     - Sub-sub-item A
     - Sub-sub-item B
     - Sub-sub-item C

** Other Elements --- abbr, sub, sup, kbd, mark
   :PROPERTIES:
   :CUSTOM_ID: other-elements-abbr-sub-sup-kbd-mark
   :END:


#+BEGIN_EXPORT html
<p><abbr title="Graphics Interchange Format">GIF</abbr> is a bitmap
image format.</p>
#+END_EXPORT

H_{2}O

X^{n} + Y^{n} = Z^{n}

#+BEGIN_EXPORT html
<p>Press <kbd>CTRL</kbd> + <kbd>ALT</kbd> + <kbd>Delete</kbd> to end
the session.</p>
#+END_EXPORT

Most salamanders are nocturnal, and hunt for insects, worms, and other
small creatures.

[fn:1] The above quote is excerpted from Rob Pike's [[https://www.youtube.com/watch?v=PAAkCSZUG1c][talk]] during
       Gopherfest, November 18, 2015.
